name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Container image
        run: docker pull docker.io/ubuntu:bionic-20180224
      - uses: anchore/scan-action@v3
        id: scan
        with:
          image: "docker.io/ubuntu:bionic-20180224"
          acs-report-enable: true
          severity-cutoff: critical
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
